language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
before_script:
  - composer install
after_script:
  - ./vendor/bin/coveralls -vvv
notifications:
  email:
    recipients:
      - sven.houtmeyers@cultuurnet.be
      - kristof@coomans.eu

